### ISSUE TITLE
Make abstract for ASIST Annual meeting available

### ISSUE THREAD

**Issue by ehenneken** [asclepias/asclepias#11]
Make the 2-page abstract for the Metrics workshop (talk) available through a public link. Either by creating a record on arXiv or Zenodo (and add it to a community actively harvested by the ADS).

**Comment by ehenneken** [comment]
[https://doi.org/10.5281/zenodo.1011088](https://doi.org/10.5281/zenodo.1011088)

**Comment by augustfly** [comment]
So we can close this, right?
